export const INPUT_NAME = {
  FIRST_INPUT: "FIRST_INPUT",
  SECOND_INPUT: "SECOND_INPUT",
};

export const CONVERSION_FLOW = {
  FIRST_TO_SECOND: "FIRST_TO_SECOND",
  SECOND_TO_FIRST: "SECOND_TO_FIRST",
};

export const CONVERTER_BOX_ID = {
  FISRT_BOX: "FIRST_BOX",
  SECOND_BOX: "SECOND_BOX",
};
